[package]
name = "nix-ffi"
version = "1.0.0"
authors = ["Shea Levy <shea.levy@scarf.sh>", "Scarf Engineering Team <engineering@scarf.sh>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
nix = "0.19.1"
os_pipe = "0.9.2"
libc = "0.2.86"
